<?php

$title = 'Blog main page';
$this->headTitle($title);
?>

<?php

echo "<p><h3>".$this->flashMessenger()->render()."</h3></p>";

if (!$isAuthenticated) {
    ?>
    <p>
        <?= $this->zfcUserLoginWidget() ?>
    </p>
    <?php
} else {
    ?>
    <a href="<?= $this->url('zfcuser/logout') ?>" class="btn btn-info">Logout</a>
    <a href="<?= $this->url('post', ['action' => 'add']) ?>" class="btn btn-info">Add post</a>
    <a href="<?= $this->url('category', ['action' => 'add']) ?>" class="btn btn-info">Add category</a>
    <?php
};
?>
    <table class="table">
        <tr>
            <th>Title</th>
            <th>Content</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
        </tr>
        <?php
        foreach ($posts as $post) : ?>

            <tr>
                <td><a href="<?php echo $this->url('post', ['action' => 'show', 'id' => $post->id]); ?>">
                        <?php echo $post->title; ?>
                    </a></td>
                <td><a href="<?php echo $this->url('post', ['action' => 'show', 'id' => $post->id]); ?>">
                        <?php echo substr($post->content, 10); ?>
                    </a></td>
                <?php
                if ($isAuthenticated) {
                    ?>
                    <td><a href="<?php echo $this->url('comment', ['action' => 'add', 'id' => $post->id]); ?>"
                           class="btn btn-info">Add comment </a></td>
                <?php }
                if ($post->user->getId() == $user_id) { ?>
                    <td>
                        <a href="<?= $this->url('post', ['action' => 'edit', 'id' => $post->id]) ?>"
                           class="btn btn-info">Edit</a>
                    </td>
                    <td>
                        <a href="<?= $this->url('post', ['action' => 'delete', 'id' => $post->id]) ?>"
                           class="btn btn-info">Delete</a>
                    </td>
                <?php } else { ?>
                    <th>&nbsp;</th>
                    <th>&nbsp;</th>
                <?php }
                ?>

            </tr>
            <?php
        endforeach; ?>
    </table>

<?php
echo $this->paginationControl($this->paginator,
    'Sliding',
    'pagination.phtml', array('route' => 'mainpage')); ?>