<?php

$title = 'Delete album';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that ypu want to delete
    '<?= $this->escapeHtml($album->title); ?>' by
    '<?= $this->escapeHtml($album->artist) ?>'?
</p>
<?php
$url = $this->url('album',[
    'action'=>'delete',
    'id'=>$this->id,
]);
?>
<form action="<?= $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?= (int) $album->id; ?>"/>
        <input type="submit" name="del" value="Yes">
        <input type="submit" name="del" value="No">
    </div>
</form>

