<?php

$title = 'Delete post';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete post:
    '<?= $this->escapeHtml($category->categoryName) ?>'?
</p>
<?php
$url = $this->url('category', [
    'action' => 'delete',
    'id' => $category->id,
]);
?>
<form action="<?= $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?= (int)$category->id; ?>"/>
        <input type="submit" name="del" value="Yes"/>
        <input type="submit" name="del" value="No"/>
    </div>
</form>