<?php

$title = 'My blog';
$this->headTitle($title);
?>

<h1>
    <?= $this->escapeHtml($title);
    ?>
</h1>
<p>
    <a href="<?= $this->url('blog', ['action' => 'add']) ?>" class="btn btn-info">Add new post</a>
    <a href="<?= $this->url('category', ['action' => 'index']) ?>" class="btn btn-info">Manage categories</a>
</p>
<table class="table">
    <tr>
        <th>Title</th>
        <th>Content</th>
        <th>Category</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($blogs as $blog) : ?>
        <tr>
            <td><?= $this->escapeHtml($blog->title); ?></td>
            <td><?= $this->escapeHtml($blog->content); ?></td>
            <td><?= $this->escapeHtml($blog->category->categoryName); ?></td>

            <td>
                <a href="<?= $this->url('comment', ['action' => 'add', 'id' => $blog->id]) ?>">Add comment</a>
            </td>
            <td>
                <a href="<?= $this->url('blog', ['action' => 'edit', 'id' => $blog->id]) ?>">Edit</a>
            </td>
            <td>
                <a href="<?= $this->url('blog', ['action' => 'delete', 'id' => $blog->id]) ?>">Delete</a>
            </td>
        </tr>

    <?php endforeach; ?>
</table>
