<?php

$title = 'Delete post';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete post:
    '<?= $this->escapeHtml($post->title) ?>'?
</p>
<?php
$url = $this->url('post', [
    'action' => 'delete',
    'id' => $post->id,
]);
?>
<form action="<?= $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?= (int)$post->id; ?>"/>
        <input type="submit" name="del" value="Yes"/>
        <input type="submit" name="del" value="No"/>
    </div>
</form>